### DISCUSSION TITLE
FIBOS mainnet upgrade

### DISCUSSION THREAD

**Discussion by wisflash** [FIBOSIO/fibos#37] [General]
# FIBOS Mainnet Upgrade

- **Introduction**: The FIBOS mainnet consensus node `koalakoalala` has been successfully upgraded. After the upgrade, the FIBOS program version is V5.0.3.0. This document will outline the upgrade process and highlight key considerations during the upgrade.

## Upgrade Preparation

1. **Prepare the New FIBOS: V5.0.3.0 Application**: (If using Docker, this step is not needed). Download using `curl`.

```bash
curl -s https://fibos.io/download/installer.sh | sh
```

2. Prepare Backup Data for the New FIBOS Full Node: The download link is https://ghost.fibos.io/new_ghost/. Use wget to download the full node backup data from the new fibos backup node to reduce synchronization time during the upgrade. After downloading, use `tar -zxvf` to extract it. The download command is as follows:

```bash
wget https://ghost.fibos.io/new_ghost/data_372196381.tar.gz
```

3. Prepare the New FIBOS Image: (Recommended to start the node using Docker). The image link is `https://hub.docker.com/r/tpblock/fibos-node/tags`, and you can pull the image using docker pull.

```bash
docker pull tpblock/fibos-node:v5.0.3.0
```

## Node Upgrade (Docker)
1. Check Local Image Library: Ensure the new image has been imported. Image repository: tpblock/fibos-node, Image tag: v5.0.3.0, Image hash: 6d70e43f2ea1.

```bash
docker images
```

2. Start with Docker or Docker Compose:

- Docker Command:

```dockerfile
docker run -d --name fibos-node -v ./fibos-node/data:/node/data -v ./resources:/app/resources \
      -p 8870:8870 -p 9870:9870 --env-file /app/resources/env.list tpblock/fibos-node:v5.0.3.0 node;
```

- Docker-Compose Command:

```yml
version: '1.0'
services:
  node-server: # Start node service
    image: tpblock/fibos-node:v5.0.3.0 # Image name
    container_name: fibos-node # Container name
    volumes:
      - ./fibos-node/data:/node/data # Mount node data directory, the mounted host directory can use the downloaded and extracted full node backup data directory to reduce sync time.
      - ./resources:/app/resources # Mount config file directory
    ports:
      - "8870:8870" # HTTP node port mapping
      - "9870:9870" # P2P node port mapping
    env_file:
      - /app/resources/env.list # Environment variables
    entrypoint: ["sh", "/app/entrypoint.sh"]  # Startup script
    command: ["node"] # Startup entry parameter (fibos index.js)
```

3. Create `resources` Directory and Files: Create `env.list`, `genesis.json`, and `p2p.json` files, which will configure container environment variables and node settings.

```bash
mkdir ./resources && cd ./resources
touch ./env.list
touch ./genesis.json
touch ./p2p.json
```

4. Example of `env.list` Environment Variables File:

```list
PRODUCER_ACCOUNT=eosio # BP account name. If this is a sync node, this parameter can be omitted.
PRODUCER_PRIVATE_KEY=5KQ****************D3 # BP private key. This parameter can be omitted for sync nodes.
PRODUCER_PUBLIC_KEY=FO6*****************CV # BP public key. This parameter can be omitted for sync nodes.
P2P_PEER_ADDRESS=35.185.138.208:10443,47.244.142.25:9870 # P2P node addresses, multiple addresses separated by commas. If not set, the default `/app/resources/p2p.json` will be used.
HTTP_PORT=8870 # HTTP port inside the container. If not set, the container uses the default port 8870.
P2P_PORT=9870 # P2P port inside the container. If not set, the container uses the default port 9870.
NODE_DIR=/node/data # Node data storage location inside the container.
SNAPSHOT_PATH=/node/data/snapshots/xxxx.bin # If using a snapshot file, set this path. (Node data must be empty for using a snapshot file, and the genesis file parameter can be omitted).
GENESIS_PATH=/app/resources/genesis.json # Path to the genesis file used by the node inside the container.
USE_WALLET=true # This parameter sets whether the node uses the wallet plugin. If it is true, the wallet and wallet_api plugins will be used
```

5. `genesis.json` File: The genesis file used for node startup should remain the same as before.

```json
{
  "initial_timestamp": "2018-08-28T00:00:00.000",
  "initial_key": "FO6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
  "initial_configuration": {
      "max_block_net_usage": 1048576,
      "target_block_net_usage_pct": 1000,
      "max_transaction_net_usage": 524288,
      "base_per_transaction_net_usage": 12,
      "net_usage_leeway": 500,
      "context_free_discount_net_usage_num": 20,
      "context_free_discount_net_usage_den": 100,
      "max_block_cpu_usage": 200000,
      "target_block_cpu_usage_pct": 1000,
      "max_transaction_cpu_usage": 150000,
      "min_transaction_cpu_usage": 100,
      "max_transaction_lifetime": 3600,
      "deferred_trx_expiration_window": 600,
      "max_transaction_delay": 3888000,
      "max_inline_action_size": 4096,
      "max_inline_action_depth": 4,
      "max_authority_depth": 6
  },
  "initial_chain_id": "6aa7bd33b6b45192465afa3553dedb531acaaff8928cf64b70bd4c5e49b7ec6a"
}
```

6. `p2p.json` File: This file contains the P2P node addresses used by the node. If there are fewer P2P addresses, you can use the `P2P_PEER_ADDRESS` configuration parameter instead. However, for a larger number of addresses, it's recommended to use the `p2p.json` configuration file. For example:

```json
[
    "182.92.152.224:9870",
    "67.205.167.7:9870",
    "165.227.83.252:9870",
    "rpc-mainnet.bitewd.com:9870",
    "39.98.64.192:9871",
    "rpc-mainnet.bitewd.com:9870",
    "35.185.138.208:10443",
    "182.92.152.224:9870",
    "bp.fo.chains.one:9876",
    "uk.fo.chains.one:9876",
    "182.92.152.224:9870",
    "35.185.138.208:10443"
]
```

## Upgrade Considerations

1. Ensure you make backups of the old data to prevent data loss if the upgrade fails. If old node data is lost, you can download the old FIBOS node data from `https://ghost.fibos.io/ghost/` to restore the node.

4. BP node upgrades should stop the old node first, then start the new node. During the upgrade, no transactions should be sent to the new node.

5. During the BP node upgrade, only the old node's BP information (username, public key, private key, etc.) needs to be filled into the `env.list` file to start the new node.
